file = open("text.txt","r")
file_content = file.readline()
file_content_1 = file.readline()
file_content_2 = file.readline()
file_content_3 = file.readline()
file_content_4 = file.readline()
print(f"1.{file_content}")
print(f"2.{file_content_1}")
print(f"3.{file_content_2}")
print(f"4.{file_content_3}")
print(f"5.{file_content_4}")